server:
  port: 8067
spring:
  servlet:
    multipart:
      maxFileSize: 9048576
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: ${dbUrl}
    username: ${username}
    password: ${password}
    driver-class-name: org.postgresql.Driver
springdoc:
  enable-native-support: true
  swagger-ui:
    path: /swagger-ui
